mongo:
  restart: always
 image: mongo:latest
 container_name: "mongodb"
 environment:
  - MONGODB_USERNAME=test
  - MONGODB_PASSWORD=test123
  - MONGODB_DATABASE=Enron
volumes:
  - ./data/db:/var/micro-data/mongodb/data/db
ports:
  - 27017:27017
command: db.createCollection(“teachers”)
