version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
    - MONGODB_USERNAME=test
    - MONGODB_PASSWORD=test123
    - MONGODB_DATABASE=enron
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: >
      bash -c "mongo --eval 'db = db.getSiblingDB(\"enron\"); db.createCollection(\"enronmails\");'"
